/**
 * Core domain types for Kaasu.
 *
 * `Transaction` is a discriminated union on `type` — the compiler enforces
 * the field rules from the spec (no category on transfer/lending, person
 * required on lending, two accounts on transfer). Illegal states are
 * unrepresentable.
 *
 * All money values are INTEGER MINOR UNITS (cents) and always positive —
 * direction of flow derives from `type`/`direction`, never a sign.
 */

export type AccountType = 'bank' | 'card' | 'cash';

export interface Account {
  id: string;
  name: string;
  type: AccountType;
  ownerLabel?: string;
  openingBalanceMinor: number;
  icon?: string;
  color?: string;
  archived: boolean;
  createdAt: string;
}

export type CategoryKind = 'expense' | 'income';

export interface Category {
  id: string;
  name: string;
  kind: CategoryKind;
  icon?: string;
  color?: string;
  isDefault: boolean;
  archived: boolean;
}

export interface Person {
  id: string;
  name: string;
  /** Created from an unrecognized voice name; needs user confirmation. */
  unresolved: boolean;
  createdAt: string;
}

export type TransactionStatus = 'pending' | 'approved' | 'rejected';
export type TransactionSource = 'voice' | 'manual' | 'recurring' | 'bill_split';

export type LendingDirection =
  | 'lend' // user gave money out — account ↓, person owes user ↑
  | 'lend_repayment_received' // they paid it back — account ↑
  | 'borrow' // user received money — account ↑, user owes person ↑
  | 'borrow_repayment_made'; // user paid them back — account ↓

/** Canonical list — spec §6. */
export type ConfidenceFlag =
  | 'unrecognized_name'
  | 'no_account_matched'
  | 'low_confidence_amount'
  | 'no_category_matched';

interface TransactionBase {
  id: string;
  status: TransactionStatus;
  /** Short title, e.g. "Boarding Rent". */
  name: string;
  /** Integer minor units (cents), always positive. */
  amountMinor: number;
  description?: string;
  /** ISO8601 — stored UTC, rendered in device-local time. */
  occurredAt: string;
  source: TransactionSource;
  /** Original spoken text when source = 'voice'. */
  transcript?: string;
  confidenceFlags: ConfidenceFlag[];
  /** Groups transactions generated by one bill split. */
  billSplitId?: string;
  /** Template that generated this transaction. */
  recurringId?: string;
  createdAt: string;
  updatedAt: string;
}

export interface ExpenseTransaction extends TransactionBase {
  type: 'expense';
  accountId: string;
  categoryId: string;
  personId?: string;
}

export interface IncomeTransaction extends TransactionBase {
  type: 'income';
  accountId: string;
  categoryId: string;
  personId?: string;
}

export interface TransferTransaction extends TransactionBase {
  type: 'transfer';
  /** Money out of this account… */
  accountId: string;
  /** …into this one. Must differ from accountId. */
  toAccountId: string;
}

export interface LendingTransaction extends TransactionBase {
  type: 'lending';
  accountId: string;
  personId: string;
  direction: LendingDirection;
}

export type Transaction =
  | ExpenseTransaction
  | IncomeTransaction
  | TransferTransaction
  | LendingTransaction;

export type TransactionType = Transaction['type'];

export type RecurringFrequency = 'daily' | 'weekly' | 'monthly' | 'custom';

/**
 * Three-state lifecycle for a template. `paused` templates skip generation
 * but keep their schedule; `cancelled` is a soft-delete that survives so its
 * generated transactions keep their link. Replaces the old `active` boolean.
 */
export type RecurringStatus = 'active' | 'paused' | 'cancelled';

/**
 * Meta grouping for the summary bar — orthogonal to `categoryId` (which still
 * drives reports/colours). A subscription can point at any category.
 */
export type RecurringGroup = 'subscription' | 'bill' | 'rent' | 'loan' | 'other';

/**
 * Stored transaction shape minus date/status, plus a schedule (spec §5).
 * Field validity per type mirrors the Transaction union but is checked at
 * generation time (templates are stored flat).
 */
export interface RecurringTemplate {
  id: string;
  type: TransactionType;
  name: string;
  amountMinor: number;
  accountId?: string;
  toAccountId?: string;
  categoryId?: string;
  personId?: string;
  direction?: LendingDirection;
  frequency: RecurringFrequency;
  /** Only for frequency = 'custom'. */
  intervalDays?: number;
  /** 'yyyy-MM-dd' local date. */
  nextDueDate: string;
  endDate?: string;
  status: RecurringStatus;
  /** 'yyyy-MM-dd' — a paused template auto-resumes on/after this date. */
  pausedUntil?: string;
  recurringGroup: RecurringGroup;
  /** Loans only: fixed number of installments. */
  totalInstallments?: number;
  /** Loans only: original principal in integer minor units. */
  principalMinor?: number;
  /** Derived convenience (= status === 'active'); kept for existing callers. */
  active: boolean;
  createdAt: string;
}
