/**
 * Report SQL builders — pure string/param construction, no database handle.
 *
 * Split out of `reports.ts` so the statements can be executed against a real
 * SQLite engine in tests (`reportSql.test.ts` uses node's built-in
 * `node:sqlite`). Everything here must stay free of `expo-sqlite` imports, or
 * the node-environment test suite can no longer load it.
 *
 * THE GOLDEN RULE (§4.1) IS ENFORCED HERE AND NOWHERE ELSE: every builder
 * hard-codes `status = 'approved'` and `type IN ('expense','income')`, so
 * transfers and lending can never reach a report through any grouping.
 *
 * PRIVATE ACCOUNTS: every builder reads from `reportRowsSql`, never straight
 * from `transactions`. That view is the user's PERSONAL money:
 *   - expense/income on personal accounts, as always;
 *   - expense/income on a private account ONLY when the report is filtered to
 *     that account (its own report);
 *   - a transfer that crosses the private boundary, re-typed: personal →
 *     private is an `expense` ("Moved to private") on the personal account,
 *     private → personal is `income` ("Back from private") on the personal
 *     account. Money leaving your finances is spending from your point of view.
 * Transfers inside one side (personal↔personal, private↔private) and all
 * lending stay out, exactly as the golden rule says.
 */

export type ReportKind = 'expense' | 'income';

/** What a donut/list can be sliced by. */
export type BreakdownDim = 'category' | 'account' | 'person' | 'recurring';

export interface ReportFilter {
  /** Inclusive local 'yyyy-MM-dd'. */
  startDay: string;
  /** Inclusive local 'yyyy-MM-dd'. */
  endDay: string;
  accountId?: string | null;
  personId?: string | null;
  /** Empty/absent means "every category". */
  includeCategoryIds?: string[] | null;
  excludeCategoryIds?: string[] | null;
}

export type Param = string | number;

export interface Statement {
  sql: string;
  params: Param[];
}

const placeholders = (n: number) => new Array(n).fill('?').join(',');

/** Category id carried by a re-typed private-boundary transfer. No real
 *  category has it (ids are UUIDs), so it can never collide. */
export const PRIVATE_TRANSFER_CATEGORY = 'private_transfer';

/**
 * The rows a report may count, as a subquery aliased `t` (same column names as
 * `transactions`, so every builder below is unchanged apart from its FROM).
 * `visibleAccountId` is the one private account whose OWN expense/income may
 * appear — the account the report is filtered to; null for none.
 */
export function reportRowsSql(visibleAccountId: string | null): Statement {
  const cols = 't.id, t.name, t.amount, t.occurred_at, t.status, t.recurring_id, t.source';
  return {
    sql: `(
       SELECT ${cols}, t.type, t.category_id, t.account_id, t.person_id
       FROM transactions t
       JOIN accounts a ON a.id = t.account_id
       WHERE t.type IN ('expense','income')
         AND (a.is_private = 0 OR a.id = ?)
       UNION ALL
       SELECT ${cols}, 'expense', '${PRIVATE_TRANSFER_CATEGORY}', t.account_id, NULL
       FROM transactions t
       JOIN accounts src ON src.id = t.account_id
       JOIN accounts dst ON dst.id = t.to_account_id
       WHERE t.type = 'transfer' AND src.is_private = 0 AND dst.is_private = 1
       UNION ALL
       SELECT ${cols}, 'income', '${PRIVATE_TRANSFER_CATEGORY}', t.to_account_id, NULL
       FROM transactions t
       JOIN accounts src ON src.id = t.account_id
       JOIN accounts dst ON dst.id = t.to_account_id
       WHERE t.type = 'transfer' AND src.is_private = 1 AND dst.is_private = 0
     ) t`,
    params: [visibleAccountId ?? ''],
  };
}

/** `FROM <report rows>` + the WHERE, with params in statement order. */
function fromRows(visibleAccountId: string | null | undefined, where: Statement): {
  from: string;
  params: Param[];
} {
  const rows = reportRowsSql(visibleAccountId ?? null);
  return { from: rows.sql, params: [...rows.params, ...where.params] };
}

/** Is a row generated by a recurring template? */
const IS_RECURRING = "(t.recurring_id IS NOT NULL OR t.source = 'recurring')";

/**
 * The shared WHERE body. `kinds` is the golden-rule gate — pass one kind for a
 * spending/earning view, both for a combined total.
 *
 * Month grouping uses SQLite's 'localtime' modifier so a 1 a.m. purchase
 * belongs to the local day, not the UTC one (timestamps are stored UTC).
 */
export function filterWhere(filter: ReportFilter, kinds: ReportKind[]): Statement {
  const clauses = [
    "t.status = 'approved'",
    `t.type IN (${placeholders(kinds.length)})`, // golden rule
    "date(t.occurred_at, 'localtime') BETWEEN ? AND ?",
  ];
  const params: Param[] = [...kinds, filter.startDay, filter.endDay];

  if (filter.accountId) {
    clauses.push('t.account_id = ?');
    params.push(filter.accountId);
  }
  if (filter.personId) {
    clauses.push('t.person_id = ?');
    params.push(filter.personId);
  }
  const include = filter.includeCategoryIds;
  if (include && include.length > 0) {
    clauses.push(`t.category_id IN (${placeholders(include.length)})`);
    params.push(...include);
  }
  const exclude = filter.excludeCategoryIds;
  if (exclude && exclude.length > 0) {
    clauses.push(`(t.category_id IS NULL OR t.category_id NOT IN (${placeholders(exclude.length)}))`);
    params.push(...exclude);
  }
  return { sql: clauses.join('\n       AND '), params };
}

export function rangeSummarySql(filter: ReportFilter): Statement {
  const where = filterWhere(filter, ['expense', 'income']);
  const { from, params } = fromRows(filter.accountId, where);
  return {
    sql: `SELECT
       COALESCE(SUM(CASE WHEN t.type = 'income'  THEN t.amount END), 0) AS incomeMinor,
       COALESCE(SUM(CASE WHEN t.type = 'expense' THEN t.amount END), 0) AS expenseMinor,
       COUNT(*) AS txCount
     FROM ${from}
     WHERE ${where.sql}`,
    params,
  };
}

export function largestTransactionSql(filter: ReportFilter, kind: ReportKind): Statement {
  const where = filterWhere(filter, [kind]);
  const { from, params } = fromRows(filter.accountId, where);
  return {
    sql: `SELECT t.id, t.name, t.amount AS amountMinor,
            CASE WHEN t.category_id = '${PRIVATE_TRANSFER_CATEGORY}' THEN ${privateTransferName} ELSE c.name END
              AS categoryName
     FROM ${from}
     LEFT JOIN categories c ON c.id = t.category_id
     WHERE ${where.sql}
     ORDER BY t.amount DESC
     LIMIT 1`,
    params,
  };
}

export function dailyTotalsSql(filter: ReportFilter): Statement {
  const where = filterWhere(filter, ['expense', 'income']);
  const { from, params } = fromRows(filter.accountId, where);
  return {
    sql: `SELECT date(t.occurred_at, 'localtime') AS day,
            COALESCE(SUM(CASE WHEN t.type = 'income'  THEN t.amount END), 0) AS incomeMinor,
            COALESCE(SUM(CASE WHEN t.type = 'expense' THEN t.amount END), 0) AS expenseMinor
     FROM ${from}
     WHERE ${where.sql}
     GROUP BY day
     ORDER BY day`,
    params,
  };
}

/** Slice name for a re-typed transfer: which way the money went. */
const privateTransferName = "(CASE t.type WHEN 'expense' THEN 'Moved to private' ELSE 'Back from private' END)";

interface DimSpec {
  join: string;
  idExpr: string;
  nameExpr: string;
  iconExpr: string;
  colorExpr: string;
  /** Extra gate, e.g. person breakdowns only count tagged rows. */
  extraWhere?: string;
}

export const DIM_SPECS: Record<BreakdownDim, DimSpec> = {
  category: {
    // LEFT join so the re-typed private-boundary transfers form their own slice.
    join: 'LEFT JOIN categories c ON c.id = t.category_id',
    idExpr: 't.category_id',
    nameExpr: `CASE WHEN t.category_id = '${PRIVATE_TRANSFER_CATEGORY}' THEN ${privateTransferName} ELSE c.name END`,
    iconExpr: `CASE WHEN t.category_id = '${PRIVATE_TRANSFER_CATEGORY}' THEN 'lock' ELSE c.icon END`,
    colorExpr: 'c.color',
    extraWhere: `(c.id IS NOT NULL OR t.category_id = '${PRIVATE_TRANSFER_CATEGORY}')`,
  },
  account: {
    join: 'JOIN accounts a ON a.id = t.account_id',
    idExpr: 'a.id',
    nameExpr: 'a.name',
    iconExpr: 'a.icon',
    colorExpr: 'a.color',
  },
  person: {
    join: 'JOIN people p ON p.id = t.person_id',
    idExpr: 'p.id',
    nameExpr: 'p.name',
    iconExpr: "'user'",
    colorExpr: 'NULL',
    extraWhere: 't.person_id IS NOT NULL',
  },
  recurring: {
    join: '',
    idExpr: `CASE WHEN ${IS_RECURRING} THEN 'recurring' ELSE 'one_off' END`,
    nameExpr: `CASE WHEN ${IS_RECURRING} THEN 'Recurring' ELSE 'One-off' END`,
    iconExpr: `CASE WHEN ${IS_RECURRING} THEN 'repeat' ELSE 'edit-3' END`,
    colorExpr: 'NULL',
  },
};

/** Ranked slices for the donut + list, largest first. */
export function breakdownSql(
  filter: ReportFilter,
  dim: BreakdownDim,
  kind: ReportKind,
): Statement {
  const spec = DIM_SPECS[dim];
  const filtered = filterWhere(filter, [kind]);
  const { from, params } = fromRows(filter.accountId, filtered);
  const where = spec.extraWhere ? `${filtered.sql}\n       AND ${spec.extraWhere}` : filtered.sql;
  return {
    sql: `SELECT ${spec.idExpr}    AS id,
            ${spec.nameExpr}  AS name,
            ${spec.iconExpr}  AS icon,
            ${spec.colorExpr} AS color,
            SUM(t.amount)     AS totalMinor,
            COUNT(*)          AS txCount
     FROM ${from}
     ${spec.join}
     WHERE ${where}
     -- Group by the EXPRESSION, never the \`id\` alias. With a join in play a
     -- bare \`id\` is ambiguous (transactions.id vs categories.id) and SQLite
     -- refuses to prepare; with no join it silently binds to transactions.id,
     -- which would emit one row per transaction instead of per slice.
     GROUP BY ${spec.idExpr}
     ORDER BY totalMinor DESC`,
    params,
  };
}

/** WHERE fragment pinning a query to one slice of a dimension. */
export function sliceWhere(dim: BreakdownDim, sliceId: string): Statement {
  switch (dim) {
    case 'category':
      return { sql: 't.category_id = ?', params: [sliceId] };
    case 'account':
      return { sql: 't.account_id = ?', params: [sliceId] };
    case 'person':
      return { sql: 't.person_id = ?', params: [sliceId] };
    case 'recurring':
      return {
        sql: sliceId === 'recurring' ? IS_RECURRING : `NOT ${IS_RECURRING}`,
        params: [],
      };
  }
}

/** Which span a drill-down is looking at. */
export type SliceScope = 'period' | 'allTime';

/**
 * WHERE for one slice, in one scope.
 *
 * 'period' honours the active period AND the rest of the report filter.
 * 'allTime' deliberately ignores both — it answers "what does this cost me
 * overall?", which is the whole point of the Overall tab. The golden rule
 * still applies in both.
 */
function sliceScopeWhere(
  filter: ReportFilter,
  dim: BreakdownDim,
  sliceId: string,
  kind: ReportKind,
  scope: SliceScope,
): { from: string; sql: string; params: Param[] } {
  const slice = sliceWhere(dim, sliceId);
  if (scope === 'allTime') {
    // The filter is ignored here, so the only private account that may show
    // is the one this slice IS (an account drill-down).
    const where = {
      sql: `t.status = 'approved'
       AND t.type = ?                              -- golden rule
       AND ${slice.sql}`,
      params: [kind, ...slice.params],
    };
    return { ...fromRows(dim === 'account' ? sliceId : null, where), sql: where.sql };
  }
  const filtered = filterWhere(filter, [kind]);
  const where = {
    sql: `${filtered.sql}
       AND ${slice.sql}`,
    params: [...filtered.params, ...slice.params],
  };
  const visible = filter.accountId ?? (dim === 'account' ? sliceId : null);
  return { ...fromRows(visible, where), sql: where.sql };
}

export function sliceStatsSql(
  filter: ReportFilter,
  dim: BreakdownDim,
  sliceId: string,
  kind: ReportKind,
  scope: SliceScope,
): Statement {
  const { from, sql, params } = sliceScopeWhere(filter, dim, sliceId, kind, scope);
  return {
    sql: `SELECT COALESCE(SUM(t.amount), 0) AS totalMinor,
            COUNT(*)                   AS txCount,
            COALESCE(MAX(t.amount), 0) AS largestMinor
     FROM ${from}
     WHERE ${sql}`,
    params,
  };
}

export function sliceLargestNameSql(
  filter: ReportFilter,
  dim: BreakdownDim,
  sliceId: string,
  kind: ReportKind,
  scope: SliceScope,
): Statement {
  const { from, sql, params } = sliceScopeWhere(filter, dim, sliceId, kind, scope);
  return {
    sql: `SELECT t.name
     FROM ${from}
     WHERE ${sql}
     ORDER BY t.amount DESC
     LIMIT 1`,
    params,
  };
}

/**
 * Lifetime figures for a slice, always across all history regardless of the
 * active scope — the drill-down shows these as context next to the period.
 */
export function sliceExtentSql(
  dim: BreakdownDim,
  sliceId: string,
  kind: ReportKind,
): Statement {
  const slice = sliceWhere(dim, sliceId);
  const where = {
    sql: `t.status = 'approved'
       AND t.type = ?                              -- golden rule
       AND ${slice.sql}`,
    params: [kind, ...slice.params],
  };
  const { from, params } = fromRows(dim === 'account' ? sliceId : null, where);
  return {
    sql: `SELECT COALESCE(SUM(t.amount), 0) AS totalMinor,
            COUNT(*)                   AS txCount,
            MIN(t.occurred_at)         AS firstOccurredAt,
            MAX(t.occurred_at)         AS lastOccurredAt
     FROM ${from}
     WHERE ${where.sql}`,
    params,
  };
}

/** Row ids making up one slice, newest first — the drill-down's list. */
export function sliceTransactionIdsSql(
  filter: ReportFilter,
  dim: BreakdownDim,
  sliceId: string,
  kind: ReportKind,
  scope: SliceScope,
): Statement {
  const { from, sql, params } = sliceScopeWhere(filter, dim, sliceId, kind, scope);
  return {
    sql: `SELECT t.id
     FROM ${from}
     WHERE ${sql}
     ORDER BY t.occurred_at DESC`,
    params,
  };
}
