/**
 * Report SQL builders — pure string/param construction, no database handle.
 *
 * Split out of `reports.ts` so the statements can be executed against a real
 * SQLite engine in tests (`reportSql.test.ts` uses node's built-in
 * `node:sqlite`). Everything here must stay free of `expo-sqlite` imports, or
 * the node-environment test suite can no longer load it.
 *
 * THE GOLDEN RULE (§4.1) IS ENFORCED HERE AND NOWHERE ELSE: every builder
 * hard-codes `status = 'approved'` and `type IN ('expense','income')`, so
 * transfers and lending can never reach a report through any grouping.
 */

export type ReportKind = 'expense' | 'income';

/** What a donut/list can be sliced by. */
export type BreakdownDim = 'category' | 'account' | 'person' | 'recurring';

export interface ReportFilter {
  /** Inclusive local 'yyyy-MM-dd'. */
  startDay: string;
  /** Inclusive local 'yyyy-MM-dd'. */
  endDay: string;
  accountId?: string | null;
  personId?: string | null;
  /** Empty/absent means "every category". */
  includeCategoryIds?: string[] | null;
  excludeCategoryIds?: string[] | null;
}

export type Param = string | number;

export interface Statement {
  sql: string;
  params: Param[];
}

const placeholders = (n: number) => new Array(n).fill('?').join(',');

/** Is a row generated by a recurring template? */
const IS_RECURRING = "(t.recurring_id IS NOT NULL OR t.source = 'recurring')";

/**
 * The shared WHERE body. `kinds` is the golden-rule gate — pass one kind for a
 * spending/earning view, both for a combined total.
 *
 * Month grouping uses SQLite's 'localtime' modifier so a 1 a.m. purchase
 * belongs to the local day, not the UTC one (timestamps are stored UTC).
 */
export function filterWhere(filter: ReportFilter, kinds: ReportKind[]): Statement {
  const clauses = [
    "t.status = 'approved'",
    `t.type IN (${placeholders(kinds.length)})`, // golden rule
    "date(t.occurred_at, 'localtime') BETWEEN ? AND ?",
  ];
  const params: Param[] = [...kinds, filter.startDay, filter.endDay];

  if (filter.accountId) {
    clauses.push('t.account_id = ?');
    params.push(filter.accountId);
  }
  if (filter.personId) {
    clauses.push('t.person_id = ?');
    params.push(filter.personId);
  }
  const include = filter.includeCategoryIds;
  if (include && include.length > 0) {
    clauses.push(`t.category_id IN (${placeholders(include.length)})`);
    params.push(...include);
  }
  const exclude = filter.excludeCategoryIds;
  if (exclude && exclude.length > 0) {
    clauses.push(`(t.category_id IS NULL OR t.category_id NOT IN (${placeholders(exclude.length)}))`);
    params.push(...exclude);
  }
  return { sql: clauses.join('\n       AND '), params };
}

export function rangeSummarySql(filter: ReportFilter): Statement {
  const { sql, params } = filterWhere(filter, ['expense', 'income']);
  return {
    sql: `SELECT
       COALESCE(SUM(CASE WHEN t.type = 'income'  THEN t.amount END), 0) AS incomeMinor,
       COALESCE(SUM(CASE WHEN t.type = 'expense' THEN t.amount END), 0) AS expenseMinor,
       COUNT(*) AS txCount
     FROM transactions t
     WHERE ${sql}`,
    params,
  };
}

export function largestTransactionSql(filter: ReportFilter, kind: ReportKind): Statement {
  const { sql, params } = filterWhere(filter, [kind]);
  return {
    sql: `SELECT t.id, t.name, t.amount AS amountMinor, c.name AS categoryName
     FROM transactions t
     LEFT JOIN categories c ON c.id = t.category_id
     WHERE ${sql}
     ORDER BY t.amount DESC
     LIMIT 1`,
    params,
  };
}

export function dailyTotalsSql(filter: ReportFilter): Statement {
  const { sql, params } = filterWhere(filter, ['expense', 'income']);
  return {
    sql: `SELECT date(t.occurred_at, 'localtime') AS day,
            COALESCE(SUM(CASE WHEN t.type = 'income'  THEN t.amount END), 0) AS incomeMinor,
            COALESCE(SUM(CASE WHEN t.type = 'expense' THEN t.amount END), 0) AS expenseMinor
     FROM transactions t
     WHERE ${sql}
     GROUP BY day
     ORDER BY day`,
    params,
  };
}

interface DimSpec {
  join: string;
  idExpr: string;
  nameExpr: string;
  iconExpr: string;
  colorExpr: string;
  /** Extra gate, e.g. person breakdowns only count tagged rows. */
  extraWhere?: string;
}

export const DIM_SPECS: Record<BreakdownDim, DimSpec> = {
  category: {
    join: 'JOIN categories c ON c.id = t.category_id',
    idExpr: 'c.id',
    nameExpr: 'c.name',
    iconExpr: 'c.icon',
    colorExpr: 'c.color',
  },
  account: {
    join: 'JOIN accounts a ON a.id = t.account_id',
    idExpr: 'a.id',
    nameExpr: 'a.name',
    iconExpr: 'a.icon',
    colorExpr: 'a.color',
  },
  person: {
    join: 'JOIN people p ON p.id = t.person_id',
    idExpr: 'p.id',
    nameExpr: 'p.name',
    iconExpr: "'user'",
    colorExpr: 'NULL',
    extraWhere: 't.person_id IS NOT NULL',
  },
  recurring: {
    join: '',
    idExpr: `CASE WHEN ${IS_RECURRING} THEN 'recurring' ELSE 'one_off' END`,
    nameExpr: `CASE WHEN ${IS_RECURRING} THEN 'Recurring' ELSE 'One-off' END`,
    iconExpr: `CASE WHEN ${IS_RECURRING} THEN 'repeat' ELSE 'edit-3' END`,
    colorExpr: 'NULL',
  },
};

/** Ranked slices for the donut + list, largest first. */
export function breakdownSql(
  filter: ReportFilter,
  dim: BreakdownDim,
  kind: ReportKind,
): Statement {
  const spec = DIM_SPECS[dim];
  const { sql, params } = filterWhere(filter, [kind]);
  const where = spec.extraWhere ? `${sql}\n       AND ${spec.extraWhere}` : sql;
  return {
    sql: `SELECT ${spec.idExpr}    AS id,
            ${spec.nameExpr}  AS name,
            ${spec.iconExpr}  AS icon,
            ${spec.colorExpr} AS color,
            SUM(t.amount)     AS totalMinor,
            COUNT(*)          AS txCount
     FROM transactions t
     ${spec.join}
     WHERE ${where}
     -- Group by the EXPRESSION, never the \`id\` alias. With a join in play a
     -- bare \`id\` is ambiguous (transactions.id vs categories.id) and SQLite
     -- refuses to prepare; with no join it silently binds to transactions.id,
     -- which would emit one row per transaction instead of per slice.
     GROUP BY ${spec.idExpr}
     ORDER BY totalMinor DESC`,
    params,
  };
}

/** WHERE fragment pinning a query to one slice of a dimension. */
export function sliceWhere(dim: BreakdownDim, sliceId: string): Statement {
  switch (dim) {
    case 'category':
      return { sql: 't.category_id = ?', params: [sliceId] };
    case 'account':
      return { sql: 't.account_id = ?', params: [sliceId] };
    case 'person':
      return { sql: 't.person_id = ?', params: [sliceId] };
    case 'recurring':
      return {
        sql: sliceId === 'recurring' ? IS_RECURRING : `NOT ${IS_RECURRING}`,
        params: [],
      };
  }
}

export function slicePeriodStatsSql(
  filter: ReportFilter,
  dim: BreakdownDim,
  sliceId: string,
  kind: ReportKind,
): Statement {
  const slice = sliceWhere(dim, sliceId);
  const { sql, params } = filterWhere(filter, [kind]);
  return {
    sql: `SELECT COALESCE(SUM(t.amount), 0) AS totalMinor,
            COUNT(*)                   AS txCount,
            COALESCE(MAX(t.amount), 0) AS largestMinor
     FROM transactions t
     WHERE ${sql}
       AND ${slice.sql}`,
    params: [...params, ...slice.params],
  };
}

export function sliceLargestNameSql(
  filter: ReportFilter,
  dim: BreakdownDim,
  sliceId: string,
  kind: ReportKind,
): Statement {
  const slice = sliceWhere(dim, sliceId);
  const { sql, params } = filterWhere(filter, [kind]);
  return {
    sql: `SELECT t.name
     FROM transactions t
     WHERE ${sql}
       AND ${slice.sql}
     ORDER BY t.amount DESC
     LIMIT 1`,
    params: [...params, ...slice.params],
  };
}

/**
 * Lifetime figures for a slice. Deliberately ignores the period AND the rest
 * of the filter, so the drill-down can answer "what does this cost me overall?"
 */
export function sliceAllTimeStatsSql(
  dim: BreakdownDim,
  sliceId: string,
  kind: ReportKind,
): Statement {
  const slice = sliceWhere(dim, sliceId);
  return {
    sql: `SELECT COALESCE(SUM(t.amount), 0) AS totalMinor,
            COUNT(*)                   AS txCount,
            MAX(t.occurred_at)         AS lastOccurredAt
     FROM transactions t
     WHERE t.status = 'approved'
       AND t.type = ?                              -- golden rule
       AND ${slice.sql}`,
    params: [kind, ...slice.params],
  };
}

/** Row ids making up one slice, newest first — the drill-down's list. */
export function sliceTransactionIdsSql(
  filter: ReportFilter,
  dim: BreakdownDim,
  sliceId: string,
  kind: ReportKind,
): Statement {
  const slice = sliceWhere(dim, sliceId);
  const { sql, params } = filterWhere(filter, [kind]);
  return {
    sql: `SELECT t.id
     FROM transactions t
     WHERE ${sql}
       AND ${slice.sql}
     ORDER BY t.occurred_at DESC`,
    params: [...params, ...slice.params],
  };
}
